### ISSUE TITLE
Support multiple gradient storage backends (ChromaDB, pgvector, Redis)

### ISSUE THREAD

**Issue by Nikhil-Prasad** [zou-group/textgrad#182]
## Description
Extend Gradient-RAG to support multiple storage backends for different deployment scenarios.

## Requirements
- **ChromaDB**: Local development, small-scale deployments
- **pgvector**: Production PostgreSQL integration
- **Redis**: High-performance caching layer
- Abstract interface for easy extension

## Implementation
```python
# Abstract interface
class GradientStore(ABC):
    @abstractmethod
    def add(self, gradient_text: str, metadata: Dict) -> str:
        pass
    
    @abstractmethod
    def search(self, query_text: str, k: int = 5) -> List[Dict]:
        pass

# Concrete implementations
class ChromaGradientStore(GradientStore):
    # ChromaDB implementation

class PgVectorGradientStore(GradientStore):
    # PostgreSQL with pgvector

class RedisGradientStore(GradientStore):
    # Redis with vector search
```

## Configuration
```yaml
gradient_rag:
  store_type: "chroma"  # or "pgvector", "redis"
  store_config:
    host: "localhost"
    port: 5432
    # Backend-specific options
```

## Benefits
- Choose backend based on deployment constraints
- Reuse existing infrastructure (PostgreSQL, Redis)
- Scale from development to production seamlessly
